# Generated by Django 2.2.16 on 2022-11-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20221127_2002'),
    ]

    operations = [
        ]
