# Generated by Django 2.2.16 on 2022-12-06 16:08

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_auto_20221205_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 6, 16, 8, 42, 789010, tzinfo=utc), verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
