# Generated by Django 2.2.16 on 2022-12-11 13:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_add_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(
                default='#006eff', image_field=None, max_length=18,
                samples=None, verbose_name='Цвет'),
        ),
     ]
