# Generated by Django 2.2.16 on 2022-12-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_add_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagRecipe',
        ),
    ]
