# Generated by Django 2.2.16 on 2022-12-06 18:50

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221205_2120'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManagerAddFields()),
            ],
        ),
    ]
